### PR TITLE
Fix typo in the-@stored-family-of-property-wrappers.json

### PR DESCRIPTION
**Pull request by Qusea**
'matter how' is repeated in 'Observing a Store’s values'

### CODE REVIEW

**Comment by mergesort** [comment]
Hey @Qusea, thank you so much for the help! I truly appreciate the effort, but I believe you've modified the wrong file to make this change.

The file you updated is one of the files Apple's docc processor automatically generates, if we fix it here then the problem will re-emerge next time the documentation is regenerated. Instead the right file to update is in the `Boutique/Sources/Boutique/Documentation.docc/Articles` folder, the `The @Stored Family Of Property Wrappers.md` located in that folder.

Would it be too much trouble to ask you to update the pull request to revert this change and update that file instead? Then I'll be able to re-run the job to regenerate the documentation.

Thank you so much!

**Comment by Qusea** [comment]
No worries, I'll get right on it

**Comment by Qusea** [comment]
I tried to revert the change, but I'm not sure if it worked. I did update the correct file though.

**Comment by mergesort** [comment]
That looks great, thanks again!

**Pull request merged**
